sudo: true

os: linux
dist: trusty

language: java
jdk:
  - oraclejdk8

before_script:
  - sudo sysctl -w net.core.rmem_max=5242880
  - sudo sysctl -w net.core.wmem_max=5242880

script:
  - mvn install failsafe:verify dependency:copy-dependencies -Pwith-sonar

after_success:
  - sonar-scanner

notifications:
  email: false

addons:
  sonarqube:
    token:
      secure: "k7jp+kk2vO0sFbweW/aV8QeoQS7PGxIPQF3yzDhdXKt9hoNetqJi/qFczjvni2LnW/Y1IGJbLOdjMymORk3jFv4lIqNbvvRnZrUDt8/K0l7hp1uW3U2EqJaQVrmEGcGYr/JTCClXm7BzDYBZ6sBCYSY4M8es3J6+Mda2a9Q8qqrr4XpIEzwMVDNzh6/Bvl7h2fddVcWa1HgqOL3inj2n7YaLfPqJAvZkW6GfVPtRoFraswG1QOqdJaHdjspafgyLzYfqlce/+Oh9oxLovBrFqwewnZwzw3WnTD5UVK7/ifuGhZQzLAhWWIMm9PaCOuQ1XPcBYVZJlFSSeTYnAeHhEJIn2CoJctbNJWyPKuq6n8TiIb4wvzUfxYPSBRQKyRRDUAXFmGKgF8UmBxAyx9hz/V67/5Qu55Aog0rFPX/lKbXk5KmwbxP5TvxtSWj1sSpU1bvbQpAnlmaMQX7Vj2Nq7rT1RDAaWTDUrYBrWz20UbbK/4GiC04kpnS4S8+xrlVBtYzAYF9o1OqSsTlkAcuO09gbfyws51gA8wHGyPTAQzaha+wwfFBaN9U6fwfuBF3/0PWon1r5KTB/L12MMT717s5oUbEDEwsh9wb+sbPAgXjz6w6xCAufFT3OKNPc9nhgZfMEeCXK3coM/HNVJb0U4ixJtk/VmNyVGJkyTWn0VVU="
    github_token:
      secure: "pFVWmfHvcAcs+iSMU/PGWvnaLn3bWl8cn2pAMjSusKwwWgq+h+kuP37xJMhU+qQDCVyBl6sWI+9IRa1Zc0kNLHUwSmnOptKVdixk0IUYTrUxrDr2oC4fiOexWqJnPxJwU/H4wyMvxoX++CifkpjSf7wPBqJL5PzQ+r9US/ySD9zl8kt2v1XbG6hGdmRj1QmedOvJhxy/wcmc1B4EB/387A0tyAlYyHaYUYp/2Cj6cL4FHsbhTPAhQVFtdpBlOiieRH9DWTFlqKPrei7J6FyRgzNtdb2ogF+T7WGekuOVbzLvzak/OrEncC3WSeiymGABnZzyu9fU3C4Rz6gVqK9EDsE4JsLPnNbZGUwdG4NPcpscjCvtsw5tWbp8C62ii2Yb6IS9LGb0ghfPwW6d1FgDDxhRnSAyjtT7xE+7zj3tcxvTlA8kZAcFL77hi7/2acbPhO8PZqUww5VBsnHvYwSgKFz9F0bjvSZg4anSL/BvdiO0jyRWawEUqAEFSAiM9tO5qVSiR/Sg3ABbr0lbgoT+VX4Ey85ufTHAn3/M4hCYamzSVd2+CSES/w8Gb3uI0tz0l1ZubgTAxgiPfJbDTAcV8QQMZzNbDpyrOa7WWr80B9QrcM7cUs1D2IS4+/eJYhwJYu6S+hpChq8jWMRu+Ik/GM+6aghMtSCeShabQDGtDOI="
    branches:
      - master
