sudo: true

language: java
jdk:
  - oraclejdk8

before_script:
  - sudo sysctl -w net.core.rmem_max=5242880
  - sudo sysctl -w net.core.wmem_max=5242880

script: mvn install failsafe:verify -Pwith-codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
